# Generated by Django 2.1.5 on 2019-02-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chose_text',
            new_name='choice_text',
        ),
    ]
